// Compiles the authored .css files into committed-ignored .generated.ts
// modules whose default export is the LightningCSS-minified CSS string.
//
// Why codegen instead of a bundler loader: the CSS must ship inlined (into
// the shadow root / an injected <style>), never as a consumer-linked
// stylesheet. Doing that through esbuild's/vite's `.css` handling fights
// their built-in CSS pipelines (which insist on emitting a standalone
// dist/*.css). A plain generated `.ts` is bundler-agnostic — tsup and vitest
// both consume it as ordinary TypeScript with zero special config, so the
// build string and the test string are identical by construction.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { transform, browserslistToTargets } from 'lightningcss';
import browserslist from 'browserslist';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', 'src');

// The toolbar/stega styles ship inline (shadow root / injected <style>), not
// as a host-linked stylesheet, so target modern evergreen browsers + Safari
// rather than a host app's browserslist. browserslistToTargets needs the
// resolved list, so run the query through browserslist() first.
const targets = browserslistToTargets(
  browserslist('>0.2%, last 2 versions, Safari >= 14, not dead')
);

/** @type {Array<{ css: string; out: string; name: string }>} */
const files = [
  {
    css: join(src, 'core/ui/toolbar.css'),
    out: join(src, 'core/ui/toolbar.generated.ts'),
    name: 'TOOLBAR_CSS',
  },
  {
    css: join(src, 'core/stega/stega.css'),
    out: join(src, 'core/stega/stega.generated.ts'),
    name: 'STEGA_STYLES',
  },
];

for (const { css, out, name } of files) {
  const { code } = transform({
    filename: css,
    code: readFileSync(css),
    minify: true,
    targets,
  });
  const banner =
    `// GENERATED by scripts/compile-css.mjs from ${css
      .split('/src/')
      .pop()} — do not edit.\n` +
    `// Run \`pnpm gen:css\` after editing the source .css file.\n`;
  writeFileSync(
    out,
    `${banner}export const ${name} = ${JSON.stringify(code.toString())};\n`
  );
  process.stdout.write(`compiled ${css.split('/src/').pop()} -> ${name}\n`);
}
